In [1]:
import pandas as pd 
fuel = pd.read_csv("/Users/arturdanyliv/Downloads/course-files/fuel.csv",usecols=["Vehicle ID","Year","Make"
                                                                                 ,"Model","Class","Fuel Type",
                                                                                 "Combined MPG (FT1)"],
                    index_col = "Vehicle ID")
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1)
Vehicle ID,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0

In [2]:
fuel['Combined KPL'] = fuel['Combined MPG (FT1)'] * 1.609 / 3.78
fuel.head()

,Year,Make,Model,Class,Fuel Type,Combined MPG (FT1),Combined KPL
Vehicle ID,,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0,8.513228
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,20.0,8.513228
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0,8.938889
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,21.0,8.938889
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,17.0,7.236243

In [3]:
fuel.insert(loc=5, column = 'liters per km', value = 100 / fuel["Combined KPL"])
fuel.head()

,Year,Make,Model,Class,Fuel Type,liters per km,Combined MPG (FT1),Combined KPL
Vehicle ID,,,,,,,,
26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,11.746426,20.0,8.513228
27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,Regular,11.746426,20.0,8.513228
26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,11.187073,21.0,8.938889
27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,Regular,11.187073,21.0,8.938889
27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Regular,13.819325,17.0,7.236243

In [8]:
del fuel["Combined MPG(FT1)"]
fuel.head()

KeyError: 'Combined MPG(FT1)'

In [9]:
fuel.drop(columns="Combined KPL", inplace=True)
fuel.head()

KeyError: "['Combined KPL'] not found in axis"