In [ ]:
# PIERDOLE NIC TU NIE DZIALA

In [6]:
import pandas as pd 
import math as math 
import matplotlib.pyplot as plt 
import numpy as np 
frame = pd.read_csv('/Users/arturdanyliv/Downloads/course-files/sleep_time.csv',index_col='name')

In [7]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt,bodywt
name,,,,,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN,50.000
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550,0.480
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN,1.350
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029,0.019
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300,600.000

In [8]:
del frame['bodywt']
# 1 SPOSOB

In [9]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt
name,,,,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300

In [10]:
frame.drop(axis=1,columns=['awake','brainwt'], inplace=True)
# pracuje domyslnie na wierszach bo axis = 1 a pozniej kolumna ktora ma byc usunieta 
# albo liste kolumn usunac 
# 2 SPOSOB

In [11]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle
name,,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8,NaN
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667

In [12]:
frame.drop(axis='columns',columns = 'sleep_cycle',inplace=True)
# 3 SPOSOB 
# columns = nazwa kolumny

In [13]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem
name,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7

In [14]:
frame.drop(columns='sleep_rem',inplace=True)
# 4 sposob najlatwiejszy okresla jakie kolumny trzeba usunac

In [15]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total
name,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1
Owl monkey,2,Aotus,omni,Primates,NaN,17.0
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0

In [25]:
# USUWANIE WIERSZY 
#frame  
#frame = pd.read_csv('/Users/arturdanyliv/Downloads/course-files/sleep_time.csv',index_col='name')

In [28]:
# Sprawdzic czemu nie dziala 
frame.drop(axis = 0, labels = [1,2], inplace=True)
frame.head()

KeyError: '[1, 2] not found in axis'

In [29]:
frame.drop(axis = 'rows',labels = 3,inplace=True)
frame.head()

KeyError: '[3] not found in axis'

In [30]:
frame.drop(labels=4,inplace=True)
frame.head()

KeyError: '[4] not found in axis'

In [31]:
frame.drop(5,inplace=True)

KeyError: '[5] not found in axis'

In [34]:
bro = frame.append({'name':'Panda4','genus':np.NaN,'vore':np.NaN,'order':np.NaN,'conversation':np.NaN,'sleep_total':10},
            ignore_index=True)

/var/folders/9q/x17lv7hn4c76lb205vp38pt00000gn/T/ipykernel_16398/2496279008.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bro = frame.append({'name':'Panda4','genus':np.NaN,'vore':np.NaN,'order':np.NaN,'conversation':np.NaN,'sleep_total':10},

In [35]:
bro.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt,bodywt,name,conversation
0,1.0,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN,50.000,NaN,NaN
1,2.0,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550,0.480,NaN,NaN
2,3.0,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN,1.350,NaN,NaN
3,4.0,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029,0.019,NaN,NaN
4,5.0,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300,600.000,NaN,NaN

In [36]:
subset = frame[0:5]
subset

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt,bodywt
name,,,,,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN,50.000
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550,0.480
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN,1.350
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029,0.019
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300,600.000

In [38]:
frame.head()

,ID,genus,vore,order,conservation,sleep_total,sleep_rem,sleep_cycle,awake,brainwt,bodywt
name,,,,,,,,,,,
Cheetah,1,Acinonyx,carni,Carnivora,lc,12.1,NaN,NaN,11.9,NaN,50.000
Owl monkey,2,Aotus,omni,Primates,NaN,17.0,1.8,NaN,7.0,0.01550,0.480
Mountain beaver,3,Aplodontia,herbi,Rodentia,nt,14.4,2.4,NaN,9.6,NaN,1.350
Greater short-tailed shrew,4,Blarina,omni,Soricomorpha,lc,14.9,2.3,0.133333,9.1,0.00029,0.019
Cow,5,Bos,herbi,Artiodactyla,domesticated,4.0,0.7,0.666667,20.0,0.42300,600.000