In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import math as math 
frame = pd.read_csv('/Users/arturdanyliv/Downloads/course-files/Mcdonalds.csv',usecols=['Item','Category','Serving Size','Calories','TotalFat'])

In [3]:
frame.head()
# ranking to nie tlko sortowanie danych to rozniez przepisanie okreslonych miejs w tym rankingu wszystkim pozycja ktore sa w danych 
# punkty rankingowe a pozniej miejsc w rankingu

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0

In [4]:
frame['Calories'].rank().head()
# zwraca obiekt serii rank()
# pozycja numer 0 egg mcmuffin otrzynuje pozycje 115
# i tak dalej 
# 1 wada ranking zobaczylismy w odrebnej serii

0    115.0
1     82.5
2    146.0
3    178.5
4    156.0
Name: Calories, dtype: float64

In [5]:
frame['CaloriesRank'] = frame['Calories'].rank()

In [6]:
frame.head()

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0,115.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0,82.5
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,23.0,146.0
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0,178.5
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0,156.0

In [8]:
frame.sort_values(by = 'Calories').head(10)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
125,Beverages,Diet Dr Pepper (Child),12 fl oz cup,0,0.0,8.5
138,Coffee & Tea,Iced Tea (Medium),21 fl oz cup,0,0.0,8.5
137,Coffee & Tea,Iced Tea (Small),16 fl oz cup,0,0.0,8.5
136,Beverages,Dasani Water Bottle,16.9 fl oz,0,0.0,8.5
145,Coffee & Tea,Coffee (Small),12 fl oz cup,0,0.0,8.5
147,Coffee & Tea,Coffee (Large),16 fl oz cup,0,0.0,8.5
124,Beverages,Diet Dr Pepper (Large),30 fl oz cup,0,0.0,8.5
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0,0.0,8.5
122,Beverages,Diet Dr Pepper (Small),16 fl oz cup,0,0.0,8.5
123,Beverages,Diet Dr Pepper (Medium),21 fl oz cup,0,0.0,8.5

In [9]:
frame.sort_values(by = 'Calories').head(20)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
125,Beverages,Diet Dr Pepper (Child),12 fl oz cup,0,0.0,8.5
138,Coffee & Tea,Iced Tea (Medium),21 fl oz cup,0,0.0,8.5
137,Coffee & Tea,Iced Tea (Small),16 fl oz cup,0,0.0,8.5
136,Beverages,Dasani Water Bottle,16.9 fl oz,0,0.0,8.5
145,Coffee & Tea,Coffee (Small),12 fl oz cup,0,0.0,8.5
147,Coffee & Tea,Coffee (Large),16 fl oz cup,0,0.0,8.5
124,Beverages,Diet Dr Pepper (Large),30 fl oz cup,0,0.0,8.5
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0,0.0,8.5
122,Beverages,Diet Dr Pepper (Small),16 fl oz cup,0,0.0,8.5
123,Beverages,Diet Dr Pepper (Medium),21 fl oz cup,0,0.0,8.5
117,Beverages,Diet Coke (Child),12 fl oz cup,0,0.0,8.5
116,Beverages,Diet Coke (Large),30 fl oz cup,0,0.0,8.5
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,8.5
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,8.5
146,Coffee & Tea,Coffee (Medium),16 fl oz cup,0,0.0,8.5
140,Coffee & Tea,Iced Tea (Child),12 fl oz cup,0,0.0,8.5
101,Snacks & Sides,Apple Slices,1.2 oz (34 g),15,0.0,17.0
100,Snacks & Sides,Side Salad,3.1 oz (87 g),20,0.0,18.0
106,Desserts,Kids Ice Cream Cone,1 oz (29 g),45,1.5,19.0
132,Beverages,Minute Maid 100% Apple Juice Box,6 fl oz (177 ml),80,0.0,20.5

In [10]:
frame['CaloriesRank'] = frame['Calories'].rank(ascending=False)
# rank(...)
# 1. method='averaga' mozna wykorzystac rozne metody budowania rankingu i to ze uzyskywalismy miejsca w rankigu 8.5 z tego averag
# 2. numric_only = None mozna okreslac czy rankingi moga byc budowan tylko ze wzgledu na wartosci numeryczne 
# 3. asceding zawsze ruwna sie true

In [11]:
frame.sort_values(by = 'Calories',ascending=False).head()
# sortujemy w katgorii maljaco

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0
34,Breakfast,Big Breakfast with Hotcakes and Egg Whites (La...,15.4 oz (437 g),1050,50.0,257.0
33,Breakfast,Big Breakfast with Hotcakes and Egg Whites (Re...,14.9 oz (423 g),990,46.0,256.0

In [12]:
frame.sort_values(by = 'Calories',ascending=False,inplace=True)
# nadani numerow poszczegolnych wartosci 
# 3 najwieksze dania 
# inplace w ramach tego obiektu

In [14]:
frame.head(3)

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0

In [16]:
frame.nlargest(n=3, columns='Calories')
# nlargest chodzi nam o largest 
# n=3 3 obiekty

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
82,Chicken & Fish,Chicken McNuggets (40 piece),22.8 oz (646 g),1880,118.0,260.0
32,Breakfast,Big Breakfast with Hotcakes (Large Biscuit),15.3 oz (434 g),1150,60.0,259.0
31,Breakfast,Big Breakfast with Hotcakes (Regular Biscuit),14.8 oz (420 g),1090,56.0,258.0

In [17]:
frame.tail(3)
# 3 najmnij kaloryczne dania

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
115,Beverages,Diet Coke (Medium),21 fl oz cup,0,0.0,8.5
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0.0,8.5
146,Coffee & Tea,Coffee (Medium),16 fl oz cup,0,0.0,8.5

In [18]:
frame.nsmallest(n=3,columns='Calories')
# 2 sposob

,Category,Item,Serving Size,Calories,TotalFat,CaloriesRank
145,Coffee & Tea,Coffee (Small),12 fl oz cup,0,0.0,8.5
140,Coffee & Tea,Iced Tea (Child),12 fl oz cup,0,0.0,8.5
139,Coffee & Tea,Iced Tea (Large),30 fl oz cup,0,0.0,8.5