In [1]:
import pandas as pd
import numpy as np

In [2]:
incidents = pd.read_csv('/Users/arturdanyliv/Downloads/course-files/Canadian Railway Crossing Incidents.csv')
incidents.set_index(['Region','EventType'],inplace=True)
incidents.sort_index(inplace=True)

In [3]:
incidents.head()
# swaplevel zamienic kolejnosc kolumn

                                   Public automated  Public passive  Private  \
Region           EventType
Alberta          Accidents                        3               7        2
                 Fatalities                       0               0        0
                 Serious injuries                 0               1        2
British Columbia Accidents                        4               1        0
                 Fatalities                       0               0        0

                                   Farm
Region           EventType
Alberta          Accidents            0
                 Fatalities           0
                 Serious injuries     0
British Columbia Accidents            0
                 Fatalities           0

In [4]:
incidents.stack().head()
# stack 
# ---> wziac najbardziej wewnetrzny poziom kolumn i przepisac go do wierszy 
# ---> w naszym przypadku mamy tylko jeden poziom kolumn 
# ---> powstanie indeks ktory sklada sie z 3 segmentow Region EventType i 3 ktory do tej pory jest kolumnami a potem pojawi sie seria danych 
# ---> zawiera te same wartosci ale ina forma 
#  przenieść nagłówki kolumn tak aby stały się kolejnym poziomem w multiindeksie.

Region   EventType
Alberta  Accidents   Public automated    3
                     Public passive      7
                     Private             2
                     Farm                0
         Fatalities  Public automated    0
dtype: int64

In [5]:
incidents.stack().to_frame().head()
# obiekt serii zamieniony na obiekt dataframe z jedna kolumna a indeks 3 kolumnowy 

# z tablicy podlznej robi sie tablica poziomowa

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [9]:
stackedIncidents = incidents.stack().to_frame()
# tworzymy zmienna

In [10]:
stackedIncidents.head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [11]:
stackedIncidents.unstack().head()
# unstack()
# gdyby zdecedowal sie przewrocic najbardziej wewnetrzny poziom indeksu do kolumn stack 
# najbardziej wewnetrzny poziom indeksu przledrowal do kolumn jak wyzej i nizej 
# Chcesz przenieść najbardziej wewnętrzny poziom multiindeksu tak aby stał się drugim członem w kolumnach.

                                                 0
                                  Public automated Public passive Private Farm
Region           EventType
Alberta          Accidents                       3              7       2    0
                 Fatalities                      0              0       0    0
                 Serious injuries                0              1       2    0
British Columbia Accidents                       4              1       0    0
                 Fatalities                      0              0       0    0

In [12]:
stackedIncidents.unstack().unstack().head()
# multi indeks stal sie normalnym indeksem i pozostala tylko wartosc dla region 
# EventTyp przeledrowala do kolumny

                                0                                             \
                 Public automated                             Public passive
EventType               Accidents Fatalities Serious injuries      Accidents
Region
Alberta                         3          0                0              7
British Columbia                4          0                3              1
Manitoba                        1          0                0              3
New Brunswick                   0          0                0              0
Newfoundland                    0          0                0              0

                                                                   \
                                               Private
EventType        Fatalities Serious injuries Accidents Fatalities
Region
Alberta                   0                1         2          0
British Columbia          0                0         0          0
Manitoba                  1                0         0          0
New Brunswick             0                0         0          0
Newfoundland              0                0         0          0


                                       Farm
EventType        Serious injuries Accidents Fatalities Serious injuries
Region
Alberta                         2         0          0                0
British Columbia                0         0          0                0
Manitoba                        0         2          0                1
New Brunswick                   0         0          0                0
Newfoundland                    0         0          0                0

In [13]:
stackedIncidents.unstack(0).head()
# unstack wykonane dla poziomu zerowego 
# na poziomie zerowym byly Region 

# nasze zestawienie alberta British Columbia itd ... prezentuje rodzaje wypadkow na roznego rodzaju przejazdow kolejowych z podzialem na poszczegolne regiony

                                  0                                          \
Region                      Alberta British Columbia Manitoba New Brunswick
EventType
Accidents  Public automated       3                4        1             0
           Public passive         7                1        3             0
           Private                2                0        0             0
           Farm                   0                0        2             0
Fatalities Public automated       0                0        0             0

                                                                            \
Region                      Newfoundland Northwest Territories Nova Scotia
EventType
Accidents  Public automated            0                     0           1
           Public passive              0                     0           0
           Private                     0                     0           0
           Farm                        0                     0           0
Fatalities Public automated            0                     0           0


Region                      Ontario Quebec Saskatchewan
EventType
Accidents  Public automated       7      4            1
           Public passive         0      0            3
           Private                2      1            0
           Farm                   0      0            0
Fatalities Public automated       1      1            0

In [14]:
stackedIncidents.unstack(level = 'Region').head()
# ktory to poziom multi indexu trzeba przelozyc do kolumny mozna uzywac nazwy rowniez 
# 2 sposob piszac level =

                                  0                                          \
Region                      Alberta British Columbia Manitoba New Brunswick
EventType
Accidents  Public automated       3                4        1             0
           Public passive         7                1        3             0
           Private                2                0        0             0
           Farm                   0                0        2             0
Fatalities Public automated       0                0        0             0

                                                                            \
Region                      Newfoundland Northwest Territories Nova Scotia
EventType
Accidents  Public automated            0                     0           1
           Public passive              0                     0           0
           Private                     0                     0           0
           Farm                        0                     0           0
Fatalities Public automated            0                     0           0


Region                      Ontario Quebec Saskatchewan
EventType
Accidents  Public automated       7      4            1
           Public passive         0      0            3
           Private                2      1            0
           Farm                   0      0            0
Fatalities Public automated       1      1            0

In [15]:
stackedIncidents.head()
# stack() i unstack()  zwraca nowy data frame nie ma inplace = True

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [16]:
stackedIncidents.unstack(level=['Region','EventType']).head()
# za jednym zamachem przer zucic do kolumn EventType i Region 
# level ---> lista kolumn ktore buduja multiindex 
# w indexie zostaly rodzaje przejazdow kolejowych

                         0                                               \
Region             Alberta                             British Columbia
EventType        Accidents Fatalities Serious injuries        Accidents
Public automated         3          0                0                4
Public passive           7          0                1                1
Private                  2          0                2                0
Farm                     0          0                0                0

                                                                   \
Region                                        Manitoba
EventType        Fatalities Serious injuries Accidents Fatalities
Public automated          0                3         1          0
Public passive            0                0         3          1
Private                   0                0         0          0
Farm                      0                0         2          0

                                                 ...                   \
Region                            New Brunswick  ...      Nova Scotia
EventType        Serious injuries     Accidents  ... Serious injuries
Public automated                0             0  ...                0
Public passive                  0             0  ...                0
Private                         0             0  ...                0
Farm                            1             0  ...                0

                                                                             \
Region             Ontario                                Quebec
EventType        Accidents Fatalities Serious injuries Accidents Fatalities
Public automated         7          1                1         4          1
Public passive           0          0                0         0          0
Private                  2          0                0         1          0
Farm                     0          0                0         0          0


Region                            Saskatchewan
EventType        Serious injuries    Accidents Fatalities Serious injuries
Public automated                0            1          0                0
Public passive                  0            3          0                0
Private                         0            0          0                0
Farm                            0            0          0                0

[4 rows x 30 columns]

In [17]:
stackedIncidents.head()
# w jaki sposob wyswietlic z regionu Alberta a z EventType Accidents tylko i wylacznie informacje o ilosci 
#   wypadkow do ktorych doszlo na prywatnych przejscciach kolejowych

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [22]:
#stackedIncidents.loc(["Alberta","Accidents","Private"])
# to co zostalo zwrocone to ciagle obiekt serii

In [23]:
stackedIncidents.loc[('Alberta','Accidents','Private'),0]
# przekazujemy parametr ktory zidentyfikuje wiersz 
# 2 afgument ktora kolumna nas interesuje (0)

2